title: Ellie Ma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! My name is Ellie. You've reached the landing page for all the projects I'm working on. These projects are a way for me to explore data and the tools and techniques used for Data Analysis and Data Science.
  <br><br>
  I have worked in Accounting, Finance, Operations, IT, System Administration, Customer Service and Support in Tech, Construction, Higher Education, and Retail. I have been interested in Data Science ever since I was an undergraduate in Mathematics, and have dabbled in using data to make decisions in every role I've had, but this is the first time I am jumping feet first into learning the tools for Data Science and Analysis. 
  <br><br>
  Feel free to reach out to me on LinkedIn with comments, questions, and feedback on these projects!
  <br><br>
  <a href="https://www.linkedin.com/in/elliecma/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-7J4YJSBELT # your Google Analytics tracking ID here
